#singleinstance, force
#commentflag //


// Generated by AutoGUI 1.4.7a
#NoEnv
#SingleInstance Force
SetWorkingDir %A_ScriptDir%

Gui Add, Edit, vin_file x16 y15 w120 h21 +ReadOnly, Input files location
Gui Add, Button, x163 y14 w80 h23, &Browse
Gui Add, Edit, vout_file x15 y54 w120 h21 +ReadOnly, Output files location
Gui Add, Button, vout_button x163 y54 w80 h23 gget_out, Browse
Gui Add, Button, x96 y96 w80 h23, &Run
Gui Show, w277 h149, Image converter
Return

GuiEscape:
GuiClose:
    ExitApp



ButtonRun:
{

	Gui, submit, hide
	Gui, new , +alwaysontop
	Gui, add, edit, vdisplay, Working on it
	Guicontrol,disable,display
	gui, -sysMenu  -toolwindow 
	Gui, show, Noactivate center ,ImageConvert2jpg

	Guicontrol,,display, Handling EPS
	loop,files, %input_path%\*.eps
	{
		
		file_name:=substr(a_loopfilename,1,instr(a_loopfilename,".")-1)
		runwait  magick convert -density 300 "%a_loopfilelongpath%" magick convert -density 300  %output_path%\%file_name%.jpg,,hide
	}

	Guicontrol,, display, Managing TIF
	loop,files, %input_path%\*.tif
	{
		file_name:=substr(a_loopfilename,1,instr(a_loopfilename,".")-1)
		runwait  magick convert -density 300 "%a_loopfilelongpath%"[0] magick convert -density 300 %output_path%\%file_name%.jpg,,hide
	}
	gui, destroy
	return
}	
	
	
	
ButtonBrowse:
{
	fileselectfolder,input_path,,,Please Select An Input File folder
	guicontrol,,in_file, %input_path%
	return
}	
	
get_out:
{
	fileselectfolder,output_path,,,Please Select An Input File folder
	guicontrol,,out_file, %output_path%
	return
}	
