#singleinstance, force
#commentflag //


// Generated by AutoGUI 1.4.7a
#NoEnv
#SingleInstance Force
SetWorkingDir %A_ScriptDir%

Gui Add, Edit, vin_file x16 y15 w120 h21 +ReadOnly, Input files location
Gui Add, Button, x163 y14 w80 h23, &Browse
Gui Add, Edit, vout_file x15 y54 w120 h21 +ReadOnly, Output files location
Gui Add, Button, vout_button x163 y54 w80 h23 gget_out, Browse
Gui Add, Button, x96 y96 w80 h23, &Run
Gui Show, w277 h149, Image converter
Return

GuiEscape:
GuiClose:
    ExitApp



ButtonRun:
{

	Gui, submit, hide
	Gui, new , +alwaysontop
	Gui, add, edit, vdisplay, Working on it
	Guicontrol,disable,display
	gui, -sysMenu  -toolwindow 
	Gui, show, Noactivate center ,ImageConvert2jpg

	loop,files, %input_path%\*.jpg
	{
		

		runwait  magick convert "%a_loopfilelongpath%" -resize 200x200 %output_path%\%a_loopfilename%,,hide
	}

return
gui,destroy
}	
	
	
	
ButtonBrowse:
{
	fileselectfolder,input_path,,,Please Select An Input File folder
	guicontrol,,in_file, %input_path%
	return
}	
	
get_out:
{
	fileselectfolder,output_path,,,Please Select An Input File folder
	guicontrol,,out_file, %output_path%
	return
}	
