#commentflag //
/*
*****************************************************************************
Gui Generated by AutoGUI 1.4.7a
Written by Jayson Scruggs
Buyer's Club Script Sceduler V1.0
Creates a scheduled task and aspect script to run an automated 
session of Procomm Plus
*****************************************************************************
*/
#NoEnv
#SingleInstance Force
SetWorkingDir %A_ScriptDir%
full_command_line := DllCall("GetCommandLine", "str")


Gui Add, CheckBox, vscript_1 genable_1 x16 y16 w163 h23, AddSkuMsgEventGroup
Gui Add, DateTime, vs1_date x203 y16 w100 h24 +Disabled, 
Gui Add, Edit, vs1_hour x350 y16 w24 h21 +Disabled +Number limit2
Gui Add, Text, x374 y14 w9 h23 +0x200, :
Gui Add, Edit, vs1_min x378 y16 w25 h21 +Disabled +Number limit2
Gui Add, Text, x315 y14 w33 h23 +0x200, Time:
Gui Add, CheckBox, vscript_2 genable_2 x16 y57 w169 h23, DelSkuMsgEventGroup
Gui Add, DateTime, vs2_date x202 y57 w100 h24 +Disabled, 
Gui Add, Text, x316 y57 w33 h23 +0x200, Time:
Gui Add, Edit, vs2_hour x350 y57 w24 h21 +Disabled +Number limit2
Gui Add, Text, x375 y56 w7 h23 +0x200, :
Gui Add, Edit, vs2_min x379 y57 w25 h21 +Disabled +Number limit2
Gui Add, Button, x177 y111 w80 h23, &GO!
Gui Show, w434 h160, Window
Return

GuiEscape:
GuiClose:
    ExitApp
	
	
	
enable_1:
{
gui, submit, nohide
	if (script_1=1)
	{
		guicontrol,enable, s1_date
		guicontrol,enable, s1_hour
		guicontrol,enable, s1_min
		Gui Show, w434 h160, Buyer's Club Script Scheduler
		return
	}
	else
	{
		guicontrol,disable, s1_date
		guicontrol,disable, s1_hour
		guicontrol,disable, s1_min
		Gui Show, w434 h160, Buyer's Club Script Scheduler
		return
	}
}


enable_2:
{
gui, submit, nohide
	if (script_2=1)
	{
		guicontrol,enable, s2_date
		guicontrol,enable, s2_hour
		guicontrol,enable, s2_min
		Gui Show, w434 h160, Buyer's Club Script Scheduler
		return
	}
	else
	{
		guicontrol,disable, s2_date
		guicontrol,disable, s2_hour
		guicontrol,disable, s2_min
		Gui Show, w434 h160, Buyer's Club Script Scheduler
		return
	}
}



buttonGO!:
{
Gui, Submit, nohide
	if (script_1=1)
	{
		if not hour_check(s1_hour)
		{
			error_show("Hour for AddSkuMsgEventGroup")
			return
		}
		if not minute_check(s1_min)
		{
			error_show("Minutes for AddSkuMsgEventGroup")
			return
		}
		script1_date:=get_date(s1_date)
		param:=script1_date s1_hour s1_min "00"
		if not (date_check(param))
		{
			error_show("AddSkuMsgEventGroup Time. Times must be scheduled for at least 2 minutes past hitting the ""GO!"" button")
			return
		}
	}
	if (script_2=1)
	{
		if not hour_check(s2_hour)
		{
			error_show("Hour for DelSkuMsgEventGroup")
			return
		}
		if not minute_check(s2_min)
		{
			error_show("Minutes for DelSkuMsgEventGroup")
			return
		}
		script2_date:=get_date(s2_date)
		param:=script2_date s2_hour s2_min "00"
		if not (date_check(param))
		{
			error_show("DelSkuMsgEventGroup Time. Times must be scheduled for at least 2 minutes past hitting the ""GO!"" button")
			return
		}
	}
	
	user:="schedule"
	pass:="shrugs"
	
	if (script_1=1)
	{
	execute=execute "AddSkuMsgEventGroup.was"
		filedelete, C:\Program Files (x86)\Symantec\Procomm Plus\Aspect\sched_add.was
		file_string:= "proc main `r`n" "transmit """ user """" "`r`n" "transmit ""^M"" `r`n" "pause 1 `r`n" "transmit """ pass  """" "`r`n" "transmit ""^M"" `r`n" "pause 1 `r`n" "transmit """ pass  """" "`r`n" "transmit ""^M"" `r`n" "transmit ""^AC^M"" `r`n" "pause 1 `r`n"
		file_string:=file_string "transmit ""a"" `r`n" "pause 3 `r`n" "transmit ""i"" `r`n" "pause 3 `r`n" "transmit ""m"" `r`n" "pause 3 `r`n" "transmit ""i"" `r`n" "pause 3 `r`n" "transmit ""a"" `r`n" "pause 3 `r`n" "transmit ""t"" `r`n" "pause 3 `r`n" "transmit ""^AH^M"" `r`n" execute "`r`n" "pause 3 `r`n" "transmit ""^AC^M"" `r`n" "transmit ""^AC^M"" `r`n" "pwexit `r`n"
		file_string:=file_string "endproc `r`n"
		fileappend,%file_string%, C:\Program Files (x86)\Symantec\Procomm Plus\Aspect\sched_add.was
		start_time:=s1_hour ":" s1_min
		run *runas c:\windows\system32\schtasks.exe /create /tn sched_add /st %Start_time% /sd %script1_date% /tr "'%a_programfiles%\Buyers_club\launcher.exe' 'sched_add.was' 'sched_add'" /sc once  /rl highest  /F   /IT,,hide
	}
	if (script_2=1)
	{
	execute=execute "DelSkuMsgEventGroup.was"
		filedelete, C:\Program Files (x86)\Symantec\Procomm Plus\Aspect\sched_del.was
		file_string:= "proc main `r`n" "transmit """ user """" "`r`n" "transmit ""^M"" `r`n" "pause 1 `r`n" "transmit """ pass  """" "`r`n" "transmit ""^M"" `r`n" "pause 1 `r`n" "transmit """ pass  """" "`r`n" "transmit ""^M"" `r`n" "transmit ""^AC^M"" `r`n" "pause 1 `r`n"
		file_string:=file_string "transmit ""a"" `r`n" "pause 3 `r`n" "transmit ""i"" `r`n" "pause 3 `r`n" "transmit ""m"" `r`n" "pause 3 `r`n" "transmit ""i"" `r`n" "pause 3 `r`n" "transmit ""a"" `r`n" "pause 3 `r`n" "transmit ""t"" `r`n" execute "`r`n" "pause 3 `r`n" "transmit ""^AC^M"" `r`n" "transmit ""^AC^M"" `r`n"  "pwexit `r`n"
		file_string:=file_string "endproc `r`n"
		fileappend,%file_string%,C:\Program Files (x86)\Symantec\Procomm Plus\Aspect\sched_del.was
		start_time:=s2_hour ":" s2_min
		run *runas c:\windows\system32\schtasks.exe /create /tn sched_del /st %Start_time% /sd %script2_date% /tr "'%a_programfiles%\Buyers_club\launcher.exe' 'sched_del.was' 'sched_del'" /sc once  /rl highest  /F   /IT,,hide
	}
	gui, destroy
	exitapp
}



hour_check(hour)
{
	if(hour>23)
		return 0
	else if (hour<02)
	{
		msgbox Scripts cannot be scheduled before 5a.m.
		return 0
	}
	else if (hour>22)
	{
		msgbox Scripts cannot be scheduled after 10p.m.
		return 0
	}
	return 1
}



minute_check(min)
{
	if(min>59)
		return 0
	return 1
}



error_show(string)
{
	Gui Show, w434 h160, Buyer's Club Script Scheduler
	msgbox Please enter a Valid %string%
	return
}



get_date(d_data) 
{
	year:=substr(d_data,1,4)
	month:=substr(d_data,5,2)
	day:=substr(d_data,7,2)
	d_data:=month "/" day "/" year 
	return d_data
}



date_check(set_date)
{
	temp:=get_date(a_now)
	temp:=temp substr(a_now,9)
	stringreplace,set_date,set_date, /,,all
	stringreplace,temp,temp, /,,all
	dif:= temp-set_date
	if (dif<-120)
		return 1
	return 0
}
